version: '3'

services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  database:
    restart: always
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgressql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432 
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres 
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6374:6379
    volumes:
      - ./cache:/data

